name: epimap-data
dependencies:
  - pandas
  - numpy
  - lxml
  - requests
  - xlrd
  - openpyxl
  - matplotlib
  - pip
  - pip:
    - geopy
    - git+git://github.com/torfjelde/covid19_datasets.git@tor/fix
